#!/usr/bin/env python
import gobject
import youamp.controller
import gettext

gettext.install("youamp")

def main():
    gobject.threads_init()

    player = youamp.controller.Controller()
    player.start()

if __name__ == "__main__":
    main()
